module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  moduleNameMapper: {
    "^@domain/(.*)$": "<rootDir>/src/domain/$1",
    "^@infrastructure/(.*)$": "<rootDir>/src/infrastructure/$1",
    "^@application/(.*)$": "<rootDir>/src/application/$1",
    "^@shared/(.*)$": "<rootDir>/src/shared/$1",
  },
  coveragePathIgnorePatterns: [
    "\\.repository\\.ts$",
    "\\.repository\\.js$",
    "\\.controller\\.ts$",
    "\\.controller\\.js$",
    "\\.entity\\.ts$",
    "\\.entity\\.js$",
    "repository\\.ts$",
    "repository\\.js$",
    "repository-persistence\\.ts$",
    "repository-persistence\\.js$",
    "\\module\\.ts$",
    "\\module\\.js$",
    "\\index\\.ts$",
    "\\index\\.js$",
    "<rootDir>/src/shared/types/*",
    "<rootDir>/src/dist/shared/types/*",
  ],
};
