/**
 * Application Fourre Tout
 * Api Rest pour ajouter, supprimer, des rendez-vous, des films, des livres, des taches
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Profile } from './profile';

export interface Tasks {
  /**
   * id
   */
  id: number;
  /**
   * title
   */
  title: string;
  /**
   * content
   */
  content: string;
  /**
   * dateFinish
   */
  dateFinish: string;
  /**
   * etat
   */
  etat: Tasks.EtatEnum;
  /**
   * profiles
   */
  profiles: Profile;
}
export namespace Tasks {
  export type EtatEnum = 'en' | 'ea' | 'fi';
  export const EtatEnum = {
    En: 'en' as EtatEnum,
    Ea: 'ea' as EtatEnum,
    Fi: 'fi' as EtatEnum,
  };
}
