/**
 * Application Fourre Tout
 * Api Rest pour ajouter, supprimer, des rendez-vous, des films, des livres, des taches
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Profile } from './profile';


export interface Appointment { 
    id: number;
    title: string;
    content: string;
    etat: Appointment.EtatEnum;
    dateAppointment: string;
    profiles: Array<Profile>;
}
export namespace Appointment {
    export type EtatEnum = 'EN' | 'AN' | 'FI';
    export const EtatEnum = {
        En: 'EN' as EtatEnum,
        An: 'AN' as EtatEnum,
        Fi: 'FI' as EtatEnum
    };
}


