"use strict";
/**
 * Application Fourre Tout
 * Api Rest pour ajouter, supprimer, des rendez-vous, des films, des livres, des taches
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateUserDtoApplication = void 0;
var CreateUserDtoApplication;
(function (CreateUserDtoApplication) {
    CreateUserDtoApplication.RoleEnum = {
        User: 'USER',
        Admin: 'ADMIN',
        Contributeur: 'CONTRIBUTEUR'
    };
})(CreateUserDtoApplication || (exports.CreateUserDtoApplication = CreateUserDtoApplication = {}));
