/**
 * Application Fourre Tout
 * Api Rest pour ajouter, supprimer, des rendez-vous, des films, des livres, des taches
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Appointment } from './appointment';
import { MovieEntity } from './movieEntity';
import { Tasks } from './tasks';
import { Favories } from './favories';
import { Books } from './books';
import { Name, Surname } from '../../../../types/profile-types';

export interface Profile {
  /**
   * id
   */
  id: number;
  /**
   * name
   */
  name: Name | null;
  /**
   * surname
   */
  surname: Surname | null;
  /**
   * favories
   */
  favories: Array<Favories>;
  /**
   * appointments
   */
  appointments: Array<Appointment>;
  /**
   * books
   */
  books: Array<Books>;
  /**
   * movies
   */
  movies: Array<MovieEntity>;
  /**
   * tasks
   */
  tasks: Array<Tasks>;
}
