"use strict";
/**
 * Application Fourre Tout
 * Api Rest pour ajouter, supprimer, des rendez-vous, des films, des livres, des taches
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MovieService = void 0;
var core_1 = require("@angular/core");
var http_1 = require("@angular/common/http");
var encoder_1 = require("../encoder");
var configuration_1 = require("../configuration");
var MovieService = function () {
    var _classDecorators = [(0, core_1.Injectable)({
            providedIn: 'root',
        })];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var MovieService = _classThis = /** @class */ (function () {
        function MovieService_1(httpClient, basePath, configuration) {
            this.httpClient = httpClient;
            this.basePath = 'http://localhost';
            this.defaultHeaders = new http_1.HttpHeaders();
            this.configuration = new configuration_1.Configuration();
            if (configuration) {
                this.configuration = configuration;
            }
            if (typeof this.configuration.basePath !== 'string') {
                var firstBasePath = Array.isArray(basePath) ? basePath[0] : undefined;
                if (firstBasePath != undefined) {
                    basePath = firstBasePath;
                }
                if (typeof basePath !== 'string') {
                    basePath = this.basePath;
                }
                this.configuration.basePath = basePath;
            }
            this.encoder = this.configuration.encoder || new encoder_1.CustomHttpParameterCodec();
        }
        // @ts-ignore
        MovieService_1.prototype.addToHttpParams = function (httpParams, value, key) {
            if (typeof value === 'object' && value instanceof Date === false) {
                httpParams = this.addToHttpParamsRecursive(httpParams, value);
            }
            else {
                httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
            }
            return httpParams;
        };
        MovieService_1.prototype.addToHttpParamsRecursive = function (httpParams, value, key) {
            var _this = this;
            if (value == null) {
                return httpParams;
            }
            if (typeof value === 'object') {
                if (Array.isArray(value)) {
                    value.forEach(function (elem) {
                        return (httpParams = _this.addToHttpParamsRecursive(httpParams, elem, key));
                    });
                }
                else if (value instanceof Date) {
                    if (key != null) {
                        httpParams = httpParams.append(key, value.toISOString().substring(0, 10));
                    }
                    else {
                        throw Error('key may not be null if value is Date');
                    }
                }
                else {
                    Object.keys(value).forEach(function (k) {
                        return (httpParams = _this.addToHttpParamsRecursive(httpParams, value[k], key != null ? "".concat(key, ".").concat(k) : k));
                    });
                }
            }
            else if (key != null) {
                httpParams = httpParams.append(key, value);
            }
            else {
                throw Error('key may not be null if value is not object or array');
            }
            return httpParams;
        };
        MovieService_1.prototype.movieApplicationControllerHandleCreateAndPublishMovie = function (createMovieApplicationDto, observe, reportProgress, options) {
            if (observe === void 0) { observe = 'body'; }
            if (reportProgress === void 0) { reportProgress = false; }
            if (createMovieApplicationDto === null ||
                createMovieApplicationDto === undefined) {
                throw new Error('Required parameter createMovieApplicationDto was null or undefined when calling movieApplicationControllerHandleCreateAndPublishMovie.');
            }
            var localVarHeaders = this.defaultHeaders;
            var localVarHttpHeaderAcceptSelected = options && options.httpHeaderAccept;
            if (localVarHttpHeaderAcceptSelected === undefined) {
                // to determine the Accept header
                var httpHeaderAccepts = ['application/json'];
                localVarHttpHeaderAcceptSelected =
                    this.configuration.selectHeaderAccept(httpHeaderAccepts);
            }
            if (localVarHttpHeaderAcceptSelected !== undefined) {
                localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
            }
            var localVarHttpContext = options && options.context;
            if (localVarHttpContext === undefined) {
                localVarHttpContext = new http_1.HttpContext();
            }
            var localVarTransferCache = options && options.transferCache;
            if (localVarTransferCache === undefined) {
                localVarTransferCache = true;
            }
            // to determine the Content-Type header
            var consumes = ['application/json'];
            var httpContentTypeSelected = this.configuration.selectHeaderContentType(consumes);
            if (httpContentTypeSelected !== undefined) {
                localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
            }
            var responseType_ = 'json';
            if (localVarHttpHeaderAcceptSelected) {
                if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                    responseType_ = 'text';
                }
                else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                    responseType_ = 'json';
                }
                else {
                    responseType_ = 'blob';
                }
            }
            var localVarPath = "/movie/create";
            return this.httpClient.request('post', "".concat(this.configuration.basePath).concat(localVarPath), {
                context: localVarHttpContext,
                body: createMovieApplicationDto,
                responseType: responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress,
            });
        };
        MovieService_1.prototype.movieApplicationControllerHandleDeleteSavedMovie = function (id, observe, reportProgress, options) {
            if (observe === void 0) { observe = 'body'; }
            if (reportProgress === void 0) { reportProgress = false; }
            if (id === null || id === undefined) {
                throw new Error('Required parameter id was null or undefined when calling movieApplicationControllerHandleDeleteSavedMovie.');
            }
            var localVarHeaders = this.defaultHeaders;
            var localVarHttpHeaderAcceptSelected = options && options.httpHeaderAccept;
            if (localVarHttpHeaderAcceptSelected === undefined) {
                // to determine the Accept header
                var httpHeaderAccepts = ['application/json'];
                localVarHttpHeaderAcceptSelected =
                    this.configuration.selectHeaderAccept(httpHeaderAccepts);
            }
            if (localVarHttpHeaderAcceptSelected !== undefined) {
                localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
            }
            var localVarHttpContext = options && options.context;
            if (localVarHttpContext === undefined) {
                localVarHttpContext = new http_1.HttpContext();
            }
            var localVarTransferCache = options && options.transferCache;
            if (localVarTransferCache === undefined) {
                localVarTransferCache = true;
            }
            var responseType_ = 'json';
            if (localVarHttpHeaderAcceptSelected) {
                if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                    responseType_ = 'text';
                }
                else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                    responseType_ = 'json';
                }
                else {
                    responseType_ = 'blob';
                }
            }
            var localVarPath = "/movie/delet/".concat(this.configuration.encodeParam({ name: 'id', value: id, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: undefined }));
            return this.httpClient.request('delete', "".concat(this.configuration.basePath).concat(localVarPath), {
                context: localVarHttpContext,
                responseType: responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress,
            });
        };
        MovieService_1.prototype.movieApplicationControllerHandleFindOneSavedMovie = function (id, observe, reportProgress, options) {
            if (observe === void 0) { observe = 'body'; }
            if (reportProgress === void 0) { reportProgress = false; }
            if (id === null || id === undefined) {
                throw new Error('Required parameter id was null or undefined when calling movieApplicationControllerHandleFindOneSavedMovie.');
            }
            var localVarHeaders = this.defaultHeaders;
            var localVarHttpHeaderAcceptSelected = options && options.httpHeaderAccept;
            if (localVarHttpHeaderAcceptSelected === undefined) {
                // to determine the Accept header
                var httpHeaderAccepts = ['application/json'];
                localVarHttpHeaderAcceptSelected =
                    this.configuration.selectHeaderAccept(httpHeaderAccepts);
            }
            if (localVarHttpHeaderAcceptSelected !== undefined) {
                localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
            }
            var localVarHttpContext = options && options.context;
            if (localVarHttpContext === undefined) {
                localVarHttpContext = new http_1.HttpContext();
            }
            var localVarTransferCache = options && options.transferCache;
            if (localVarTransferCache === undefined) {
                localVarTransferCache = true;
            }
            var responseType_ = 'json';
            if (localVarHttpHeaderAcceptSelected) {
                if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                    responseType_ = 'text';
                }
                else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                    responseType_ = 'json';
                }
                else {
                    responseType_ = 'blob';
                }
            }
            var localVarPath = "/movie/".concat(this.configuration.encodeParam({ name: 'id', value: id, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: undefined }));
            return this.httpClient.request('get', "".concat(this.configuration.basePath).concat(localVarPath), {
                context: localVarHttpContext,
                responseType: responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress,
            });
        };
        MovieService_1.prototype.movieApplicationControllerHandleFindSavedMoviesList = function (observe, reportProgress, options) {
            if (observe === void 0) { observe = 'body'; }
            if (reportProgress === void 0) { reportProgress = false; }
            var localVarHeaders = this.defaultHeaders;
            var localVarHttpHeaderAcceptSelected = options && options.httpHeaderAccept;
            if (localVarHttpHeaderAcceptSelected === undefined) {
                // to determine the Accept header
                var httpHeaderAccepts = [];
                localVarHttpHeaderAcceptSelected =
                    this.configuration.selectHeaderAccept(httpHeaderAccepts);
            }
            if (localVarHttpHeaderAcceptSelected !== undefined) {
                localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
            }
            var localVarHttpContext = options && options.context;
            if (localVarHttpContext === undefined) {
                localVarHttpContext = new http_1.HttpContext();
            }
            var localVarTransferCache = options && options.transferCache;
            if (localVarTransferCache === undefined) {
                localVarTransferCache = true;
            }
            var responseType_ = 'json';
            if (localVarHttpHeaderAcceptSelected) {
                if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                    responseType_ = 'text';
                }
                else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                    responseType_ = 'json';
                }
                else {
                    responseType_ = 'blob';
                }
            }
            var localVarPath = "/movie/list";
            return this.httpClient.request('get', "".concat(this.configuration.basePath).concat(localVarPath), {
                context: localVarHttpContext,
                responseType: responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress,
            });
        };
        MovieService_1.prototype.movieApplicationControllerHandleUpdateMovieDetail = function (updateMovieApplicationDto, observe, reportProgress, options) {
            if (observe === void 0) { observe = 'body'; }
            if (reportProgress === void 0) { reportProgress = false; }
            if (updateMovieApplicationDto === null ||
                updateMovieApplicationDto === undefined) {
                throw new Error('Required parameter updateMovieApplicationDto was null or undefined when calling movieApplicationControllerHandleUpdateMovieDetail.');
            }
            var localVarHeaders = this.defaultHeaders;
            var localVarHttpHeaderAcceptSelected = options && options.httpHeaderAccept;
            if (localVarHttpHeaderAcceptSelected === undefined) {
                // to determine the Accept header
                var httpHeaderAccepts = ['application/json'];
                localVarHttpHeaderAcceptSelected =
                    this.configuration.selectHeaderAccept(httpHeaderAccepts);
            }
            if (localVarHttpHeaderAcceptSelected !== undefined) {
                localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
            }
            var localVarHttpContext = options && options.context;
            if (localVarHttpContext === undefined) {
                localVarHttpContext = new http_1.HttpContext();
            }
            var localVarTransferCache = options && options.transferCache;
            if (localVarTransferCache === undefined) {
                localVarTransferCache = true;
            }
            // to determine the Content-Type header
            var consumes = ['application/json'];
            var httpContentTypeSelected = this.configuration.selectHeaderContentType(consumes);
            if (httpContentTypeSelected !== undefined) {
                localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
            }
            var responseType_ = 'json';
            if (localVarHttpHeaderAcceptSelected) {
                if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                    responseType_ = 'text';
                }
                else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                    responseType_ = 'json';
                }
                else {
                    responseType_ = 'blob';
                }
            }
            var localVarPath = "/movie/update";
            return this.httpClient.request('put', "".concat(this.configuration.basePath).concat(localVarPath), {
                context: localVarHttpContext,
                body: updateMovieApplicationDto,
                responseType: responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress,
            });
        };
        return MovieService_1;
    }());
    __setFunctionName(_classThis, "MovieService");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        MovieService = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return MovieService = _classThis;
}();
exports.MovieService = MovieService;
